version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node
    steps:
      - run: npm test

workflows:
  build-test:
    jobs:
      - build
      - test
